FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libasound2-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["/bin/bash", "-c", "mkdir -p build_linux && cd build_linux && cmake .. && make"]
